version: "3"
services:
    web:
        image: daocloud.io/buxiaomo/ssserverweb:latest
        hostname: ssserver_web
        ports:
            - 80:8000/tcp
        environment:
            - ALIYUN_ID=xxxxxx
            - ManagerIP=xxx.xxx.xxx.xxx
            - ALIYUN_Secret=xxxxxx
            - DomainName=xxxxxx
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        deploy:
            mode: global
            placement:
                constraints: [node.role == manager]
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000"]
            interval: 3s
            timeout: 1s
            retries: 5
        networks:
            - ssserver
networks:
    ssserver:
        external: true
